window.REGISTROS_PUBLICOS = [
  {
    "nombre_completo": "Arditto Bejarano, Jimmy Alexander",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "25760299",
    "documento_mask": "DNI 2576****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260010299",
    "estado": "VÁLIDO",
    "nota": "18.00",
    "codigo_registro": "20260299142"
  },
  {
    "nombre_completo": "Ccanto Huayllani, Lorgio Antonio",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "42084895",
    "documento_mask": "DNI 4208****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260024895",
    "estado": "VÁLIDO",
    "nota": "16.00",
    "codigo_registro": "20264895144"
  },
  {
    "nombre_completo": "Salas Pariona, Freddy",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "20993469",
    "documento_mask": "DNI 2099****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260033469",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20263469145"
  },
  {
    "nombre_completo": "Palomino Camero, Pedro",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "03885121",
    "documento_mask": "DNI 0388****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260045121",
    "estado": "VÁLIDO",
    "nota": "19.00",
    "codigo_registro": "20265121146"
  },
  {
    "nombre_completo": "Calderón Anduaga, Jaime",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "09679293",
    "documento_mask": "DNI 0967****",
    "tipo_documento": "Especialización",
    "condicion_obtenida": "Especialista",
    "denominacion_programa": "Gerencia de Seguridad y Criminología",
    "tipo_programa": "Programa de Alta Especialización",
    "fecha_emision": "25/08/2026",
    "horas_academicas": "384",
    "codigo_emision": "PAEGSC20260019293",
    "estado": "VÁLIDO",
    "nota": "19.17",
    "codigo_registro": "20269293008",
    "codigo_certificado_relacionado": "CERTGSC20260001"
  },
  {
    "nombre_completo": "Huaypuna Ccalla, Eloy Zenón",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "80320361",
    "documento_mask": "DNI 8032****",
    "tipo_documento": "Especialización",
    "condicion_obtenida": "Especialista",
    "denominacion_programa": "Gerencia de Seguridad y Criminología",
    "tipo_programa": "Programa de Alta Especialización",
    "fecha_emision": "25/08/2026",
    "horas_academicas": "384",
    "codigo_emision": "PAEGSC20260020361",
    "estado": "VÁLIDO",
    "nota": "19.83",
    "codigo_registro": "20260361155",
    "codigo_certificado_relacionado": "CERTGSC20260002"
  },
  {
    "nombre_completo": "Pacheco Argandoña, Oscar Vitaliano",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "44239116",
    "documento_mask": "DNI 4423****",
    "tipo_documento": "Especialización",
    "condicion_obtenida": "Especialista",
    "denominacion_programa": "Gerencia de Seguridad y Criminología",
    "tipo_programa": "Programa de Alta Especialización",
    "fecha_emision": "25/08/2026",
    "horas_academicas": "384",
    "codigo_emision": "PAEGSC20260039116",
    "estado": "VÁLIDO",
    "nota": "19.17",
    "codigo_registro": "20259116015",
    "codigo_certificado_relacionado": "CERTGSC20260003"
  },
  {
    "nombre_completo": "Arevalo Lozano, Julio Cesar",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "44241195",
    "documento_mask": "DNI 4424****",
    "tipo_documento": "Especialización",
    "condicion_obtenida": "Especialista",
    "denominacion_programa": "Gerencia de Seguridad y Criminología",
    "tipo_programa": "Programa de Alta Especialización",
    "fecha_emision": "25/08/2026",
    "horas_academicas": "384",
    "codigo_emision": "PAEGSC20260041195",
    "estado": "VÁLIDO",
    "nota": "19.50",
    "codigo_registro": "20261195002",
    "codigo_certificado_relacionado": "CERTGSC20260004"
  },
  {
    "nombre_completo": "Reategui Tomanguilla, Wilner",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "43289107",
    "documento_mask": "DNI 4328****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260059107",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20269107147"
  },
  {
    "nombre_completo": "Rengifo Rico, Jorge Rolando Rengifo Rico",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "09990173",
    "documento_mask": "DNI 0999****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260060173",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20260173149"
  },
  {
    "nombre_completo": "Bazalar Cantera, Walter Jorge",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "15727642",
    "documento_mask": "DNI 1572****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260077642",
    "estado": "VÁLIDO",
    "nota": "14.00",
    "codigo_registro": "20267642150"
  },
  {
    "nombre_completo": "Calderón Anduaga, Jaime",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "09679293",
    "documento_mask": "DNI 0967****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260089293",
    "estado": "VÁLIDO",
    "nota": "19.00",
    "codigo_registro": "20269293008"
  },
  {
    "nombre_completo": "Del Pino Ortega, Henry Victor",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "29598898",
    "documento_mask": "DNI 2959****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260098898",
    "estado": "VÁLIDO",
    "nota": "18.00",
    "codigo_registro": "20268898003"
  },
  {
    "nombre_completo": "Ruidias Calle, José Luis",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "40145606",
    "documento_mask": "DNI 4014****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260105606",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20265606162"
  },
  {
    "nombre_completo": "Vilela Castillo, Carlos Jesus",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "06061975",
    "documento_mask": "DNI 0606****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260111975",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20261975172"
  },
  {
    "nombre_completo": "Portella Cardenas, Stephano Luciano",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "42222626",
    "documento_mask": "DNI 4222****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260122626",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20262626173"
  },
  {
    "nombre_completo": "Saldaña Pérez, Marcos Noé",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "40450743",
    "documento_mask": "DNI 4045****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260130743",
    "estado": "VÁLIDO",
    "nota": "20.00",
    "codigo_registro": "20260743026"
  },
  {
    "nombre_completo": "Palomino Camero, Pedro",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "03885121",
    "documento_mask": "DNI 0388****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260145121",
    "estado": "VÁLIDO",
    "nota": "19.00",
    "codigo_registro": "20265121146"
  },
  {
    "nombre_completo": "Leon Alca, Gerardo Crispin",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "43601862",
    "documento_mask": "DNI 4360****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260151862",
    "estado": "VÁLIDO",
    "nota": "18.00",
    "codigo_registro": "20261862187"
  },
  {
    "nombre_completo": "Falcón Calderon, Hermias Manuel",
    "tipo_doc_identidad": "DNI",
    "numero_documento": "09934549",
    "documento_mask": "DNI 0993****",
    "tipo_documento": "Certificado",
    "condicion_obtenida": "Aprobado",
    "denominacion_programa": "Gestión del Servicio de Serenazgo Municipal",
    "tipo_programa": "Curso Especializado",
    "fecha_emision": "26/08/2026",
    "horas_academicas": "48",
    "codigo_emision": "CURGSSM20260164549",
    "estado": "VÁLIDO",
    "nota": "18.00",
    "codigo_registro": "20264549196"
  }
];
